### ISSUE TITLE
The live preview and download pdf are not working properly, can you please assign this issue to me by today so that I can fix that.

### ISSUE THREAD

**Issue by Luson045** [SandeepVashishtha/LaTeX-Resume-Builder#12]
There are a few issues with the live preview and download pdf feature, I want to fix it.. also I want to know if the backend is hosted separately.

**Comment by SandeepVashishtha** [comment]
Ok pls fix it 
And i have to deploy backend on azure

**Comment by Luson045** [comment]
Can you please provide me the api for the backend, as currently you are making calls to localhost which is not valid.

**Comment by SandeepVashishtha** [comment]
@Luson045 https://latex-resume-builder.onrender.com url for backend service

**Comment by Luson045** [comment]
https://github.com/user-attachments/assets/08d296ee-efe9-486f-be55-ed0d804d5df1


fixed the live preview and download pdf option ++ added some styling and some latex commands for user's understanding, I'm giving pr?
