### ISSUE TITLE
UI Fixes and Improvements on Home Page

### ISSUE THREAD

**Issue by SandeepVashishtha** [SandeepVashishtha/LaTeX-Resume-Builder#16]
Need assistance to fix and improve the UI on the home page of the LaTeX Resume Builder application. Specific areas needing attention include:

- Updating the layout for better user experience.
- Enhancing the responsiveness for different screen sizes.
- Improving the overall aesthetic to be more modern and user-friendly.

Something Like this :-
![Screenshot 2024-10-13 225959](https://github.com/user-attachments/assets/eb7a13fe-cac6-47bf-a004-1e3bd403054b)

**Comment by TusharGupta-Developer** [comment]
Hi @SandeepVashishtha , I would like to work on this issue. Could you please assign it to me? Thanks!

**Comment by TusharGupta-Developer** [comment]
Hi @SandeepVashishtha, I hope this message finds you well. I wanted to inform you that I have implemented a design for the Home Page that differs from your initial request. I believe this new design is more user-friendly and enhances the overall experience.
Please let me know if you would like any adjustments to align with your original vision.

**Comment by SandeepVashishtha** [comment]
@TusharGupta-Developer your PR fixes the problem but i think that live preview and latex editor should be side by side so that the user can see live preview easily. Btw nice work done ✅
